### ISSUE TITLE
contacts.upsert   is not working

### ISSUE THREAD

**Issue by raphaelvserafim** [salman0ansari/whatsapp-api-nodejs#405] opened 2022-11-10 00:22 UTC
The  contacts.upsert event stopped working for me

 ```JS 
     sock?.ev.on("contacts.upsert", (contacts) => {
            console.log("contacts.upsert", contacts);
        });

```

**Comment by salman0ansari** [comment] 2022-11-11 18:45
duplicate of https://github.com/adiwajshing/Baileys/issues/2316

**Closed by salman0ansari** 2022-11-11 18:45 UTC
