### ISSUE TITLE
stop in Docker

### ISSUE THREAD

**Issue by wisnubaldas** [salman0ansari/whatsapp-api-nodejs#28] opened 2022-02-27 08:14 UTC
container stops after some time there is an error too many requests
![Jepretan Layar 2022-02-27 pukul 15 11 11](https://user-images.githubusercontent.com/10908214/155874387-4a75c82a-b22a-4050-9b60-30786e0dbd02.png)

**Comment by manojsitapara** [comment] 2022-02-27 08:28
please scan qr as soon as possible

**Comment by salman0ansari** [comment] 2022-03-01 13:35
duplicate of (#19)

**Closed** 2022-03-03 17:31 UTC
Labels: duplicate
