### ISSUE TITLE
Delivery confirmation

### ISSUE THREAD

**Issue by bmbraga** [salman0ansari/whatsapp-api-nodejs#150] opened 2022-06-15 20:54 UTC
How can I confirm that a message was actually delivered? This week has increased the number of messages that are not delivered, with status = PENDING.
How can I see the real status and how is the send queue?

**Comment by salman0ansari** [comment] 2022-06-15 21:22
duplicate of #77

**Comment by Zarinia** [comment] 2022-06-19 11:25
You can check 
```
ev.on('messages.update', async (messages) => {
console.dir(messages);
for (const message of messages) {
is_delivered = message?.update?.status === 3;
is_seen = message?.update?.status === 4
}
})
```

with this socket, every time that message status changes this socket fires and notifies you

**Closed** 2022-06-28 12:27 UTC
Labels: enhancement, question

**Comment by pauloanalista** [comment] 2023-02-04 12:17
Can you raise a PR with this solution?

Do you receive via webhook?

**Comment by sairmali** [comment] 2023-07-22 11:12
@bmbraga how can i implement this for message status
